### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Thordekk** [Razzue/Wow-Dumper#3]
hi can u explain how to use the dumper?

**Comment by Razzue** [comment]
- Dump Wow
- Find Offset
- Make pattern to offset
- Add new pattern (?? for wildcards) to dumper(Take a look at TBC/SOM example classes)
- Run Dumper
- Run Wow
- Input process id of wow to console and smack enter
- Sit back and twiddle your thumbs.

This is not the purpose of issues. My discord is posted publicly in my bio, though I do not partake/believe in hand holding.
Closed.
